on:
  pull_request:
    types: [opened, synchronize]
    branches: [staging]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test

    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.6

      - run: bun install --frozen-lockfile
      - run: bun run format:ci
      - run: bun run typecheck
      - run: bun run lint
      - run: bun run test
      - run: bun run migrate:ci
        env:
          POSTGRES_PRISMA_URL: ${{ secrets.POSTGRES_PRISMA_URL_PREVIEW }}
          POSTGRES_URL_NON_POOLING: ${{ secrets.POSTGRES_URL_NON_POOLING_PREVIEW }}
